apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-bit-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fluent-bit-secrets
  data:
  - secretKey: es-username
    remoteRef:
      key: logging/es-fluentd
      property: user
  - secretKey: es-password
    remoteRef:
      key: logging/es-fluentd
      property: password  