apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - fluent-bit-externalsecret.yaml
  - fluent-bit-config.yaml

# patch values.yaml?
configMapGenerator:
  - name: fluent-bit-helm-values
    behavior: merge
    files:
      - forwarding-values.yaml=values.yaml

patches:
- target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: fluent-bit
  path: helm-patch.yaml