---

- name: "Wait for master node to be ready"
  ansible.builtin.command:
    cmd: "kubectl get nodes {{ item }}"
  register: nodes
  until:
    - '" Ready "  in nodes.stdout'
  retries: 10
  delay: 5
  with_items: "{{ inventory_hostname }}"
