---
# Get list of packages installed
- name: Get list of packages
  ansible.builtin.package_facts:
    manager: auto

- name: Remove snap package
  ansible.builtin.include_tasks: remove_snap.yaml
  when: >
    'snapd' in ansible_facts.packages
    and 'maas' not in group_names

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    update_cache: true
    state: present

- name: Execute Radxa Rock 5B+ specific setup tasks
  ansible.builtin.include_tasks: radxa_tasks.yaml
  when: "'radxa' in group_names"

- name: Load required Kernel modules
  ansible.builtin.include_tasks: load_kernel_modules.yaml

- name: Blacklist storage devices in multipath configuration
  ansible.builtin.include_tasks: multipath_blacklist.yaml
