---
# service node variables

########################
# Bind9 role variables
########################

bind9_authoritative: true
bind9_forward: true
bind9_recursor: true
bind9_forward_servers: [9.9.9.11, 194.112.112.11]
bind9_generate_ddns_key: true
bind9_zones:
  - name: "{{ dns_domain }}"
    type: primary
    ddns_update_key: ddnskey
    ddns_update_policy_grant: "zonesub any"
    secondary_servers:
      - 'key "ddnskey"'
    default_ttl: 600
    serial: 2025061400
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}"
    # RR values are either relative to the zone, either with a final dot when outside.
    rrs:
      - label: gateway
        type: A
        rdata: 10.20.0.1
      - label: ns
        type: A
        rdata: 10.20.0.8
      - label: vault
        type: A
        rdata: 10.20.0.8
      - label: service0
        type: A
        rdata: 10.20.0.8
      - label: s3
        type: A
        rdata: 10.20.0.8
      - label: ns.maas
        type: A
        rdata: 10.20.0.10
      - label: maas
        type: NS
        rdata: ns.maas
  - name: 10.in-addr.arpa
    type: primary
    default_ttl: 600
    serial: 2025061400
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}."
    rrs:
      - label: 1.0.20
        type: PTR
        rdata: "gateway.{{ dns_domain }}."
      - label: 20
        type: NS
        rdata: "prime.{{ dns_domain }}."

############################
# restic backup role variables
############################
restic_clean_service: true
