---
# service node variables

############################
# restic backup role variables
############################
restic_clean_service: true

############################
# vault role variables
############################
vault_venv_path: "/opt/vault-venv"
