---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eck-operator-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: elastic
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/eck-operator/app/overlays/prod
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-stack-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: elastic
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: eck-operator-app
    - name: longhorn-app
    - name: external-secrets-config
  path: ./kubernetes/platform/elastic-stack/app/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Elasticsearch
      failed: status.health in ["yellow","red"]
      current: status.health in ["green"]
    - apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Kibana
      failed: status.health in ["yellow","red"]
      current: status.health in ["green"]
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-elasticsearch-exporter-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: elastic
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: elastic-stack-app
  path: ./kubernetes/platform/elastic-stack/prometheus-elasticsearch-exporter/overlays/prod
  prune: true
  wait: true