---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kube-prometheus-stack-k3s-mixins
    - name: tempo-app
    - name: loki-app
    - name: external-secrets-config
  path: ./kubernetes/platform/grafana/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings

