---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium-config
    - name: coredns-app
  path: ./kubernetes/platform/istio/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-ingress
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-app
  path: ./kubernetes/platform/istio/gateway/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings