---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kiali-operator-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kiali
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/kiali/app/overlays/prod
  prune: true
  dependsOn:
    - name: istio-app
    - name: keycloak-app
    - name: grafana-app
    - name: tempo-app
    - name: kube-prometheus-stack-app
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings