---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-app
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: longhorn-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx-app
    - name: csi-external-snapshotter-app
    - name: external-secrets-config
  path: ./kubernetes/platform/longhorn/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings
