---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-community-operator-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: mongodb
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-app
  path: ./kubernetes/platform/mongodb-community-operator/app/overlays/prod
  prune: true
  wait: true
