---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: oauth2-proxy
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-config
  path: ./kubernetes/platform/oauth2-proxy/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: domain-settings
