apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-bit-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fluent-bit-secrets
  data:
  - secretKey: fluentd-shared-key
    remoteRef:
      key: logging/fluentd
      property: shared_key