---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh-charts
spec:
  url: https://aureq.github.io/cert-manager-webhook-ovh
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: 0.7.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh-charts
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: webhook-ovh-helm-values
      valuesKey: base-values.yaml
