apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluentd-certificate.yaml
  - fluentd-externalsecret.yaml
  - fluentd-extservice.yaml
  - fluentd-config.yaml
  - fluentd-elastic-templates-cm.yaml
  - helm.yaml

configMapGenerator:
  - name: fluentd-helm-values
    files:
      - base-values.yaml=values.yaml
  - name: fluentd-env
    options:
      # Disable hashing.
      # Automatic replacement does not work with configMaps references in values.yaml
      disableNameSuffixHash: true
    literals: 
      - lokiURL="http://loki-gateway.loki"
      - elasticsearchHost=efk-es-http.elastic

configurations:
  - kustomizeconfig.yaml