---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  EXTERNAL_DNS_SERVER: 10.20.0.1
  OVH_API_ENDPOINT: ovh-eu
  NGINX_LOAD_BALANCER_IP: 10.0.0.65
  FLUENTD_LOAD_BALANCER_IP: 10.0.0.66
  ISTIO_GATEWAY_LOAD_BALANCER_IP: 10.0.0.67

  PI_ADMIN_FIRSTNAME: Da
  PI_ADMIN_LASTNAME: Shi
