---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  EXTERNAL_DNS_SERVER: 10.20.0.1
  NGINX_LOAD_BALANCER_IP: 10.0.0.65
  FLUENTD_LOAD_BALANCER_IP: 10.0.0.66
  ISTIO_GATEWAY_LOAD_BALANCER_IP: 10.0.0.67