# fluent-bit helm values (monitoring)

# Enable Prometheus operator service monitor
serviceMonitor:
  enabled: true

# Enable Grafana dashboard
dashboards:
  enabled: true
  labelKey: grafana_dashboard
  labelValue: 1
  annotations:
    grafana_folder: "Logging"