apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kiali
  data:
  - secretKey: oidc-secret
    remoteRef:
      key: kiali/oauth2
      property: client-secret