---
- name: Configure DNS authoritative
  hosts: dns
  gather_facts: true
  tags: [dns]
  become: true
  pre_tasks:
    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yml"
      tags: ["always"]
  roles:
    # DNS configuration
    - role: ricsanfre.bind9

- name: Switch Vyos to our new DNS
  vyos.vyos.vyos_system:
    name_servers:
      - "{{ hostvars[groups['dns'][0]].ansible_host }}"
