---
# Deploy fluentbit to get logs and prometheus metrics
- name: Deploy fluentbit on gateway
  hosts: gateways
  gather_facts: true
  tags: [logging]
  become: true
  pre_tasks:
    # Include vault variables
    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yml"
      tags: ["always"]
    # Include picluster variables
    - name: Include picluster variables
      ansible.builtin.include_vars: "vars/picluster.yml"
      tags: ["always"]
  roles:
    - role: logging/external_node
      tags: ['logging']
