---

- name: Initialise Rdx Cluster Gateway (Ubuntu)
  hosts: gateway0i
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Collect credentials
      vars_prompt:
      - name: wifi_bssid
        prompt: Enter WiFi AP BSSID
        private: true
      - name: wifi_password
        prompt: Enter WiFI Password
        private: true
  vars:
    - netplan_apply: false  # Don't apply netplan, it will kill this connection
    - sshd_allow_reload: false  # Don't apply new SSH config, might also kill the connection
    - sshd_allow_restart: false  # Same as above.
    - firewall_apply: false # Don't apply firewall, only stage
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]
    # SSH configuration and hardening
    - role: willshersystems.sshd
      tags: [security]
    # Setup the authoritative DNS
    - role: ricansfre.dns
      tags: [dns]
    # Interface and routing configuration
    - role: mrlesmithjr.netplan
      tags: [networking]
    # Firewall (nftables) configuration
    - role: ricsanfre.firewall
      tags: [firewall]
    # NTP Server configuration
    - role: ricsanfre.ntp
      tags: [ntp]
  register: init_result

- name: Reboot if there was a change.
  command: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: init_result is changed
