---
- name: Configure Vault
  hosts: localhost
  gather_facts: false

  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config

  pre_tasks:
    # Install Python PIP and jq utility packages
    - name: Ensure required packages are installed.
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-setuptools
          - jq
        state: present
      become: true
    # Install kubernetes python packages (Ansible kubernetes collection dependency)
    - name: Ensure kubernetes Python library is installed.
      ansible.builtin.pip:
        name: kubernetes
        state: present
      become: true
    # Install Hashicorp python packages (Ansible hashi module dependency)
    - name: Ensure hashicorp vault python library is installed.
      ansible.builtin.pip:
        name: hvac
        state: present
      become: true

    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yaml"

    - name: Include picluster variables
      ansible.builtin.include_vars: "vars/picluster.yaml"

  tasks:
    - name: Set overlay to prod in case not defined by an input argument
      set_fact:
        overlay: "prod"
      when: overlay is undefined

    - name: Configure Vault integration
      include_tasks: tasks/configure_vault_integration.yaml
