---

- name: Configure Rdx Cluster Gateway (Ubuntu)
  hosts: gateway
  gather_facts: true
  tags: [gateway]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Collect credentials
      vars_prompt:
      - name: wifi_bssid
        prompt: Enter WiFi AP BSSID
        private: true
      - name: wifi_password
        prompt: Enter WiFI Password
        private: true
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]

    # SSH configuration and hardening
    - role: willshersystems.sshd
      tags: [security]

    # Setup the authoritative DNS
    - role: ricansfre.dns
      tags: [dns]

    # Interface and routing configuration
    - role: mrlesmithjr.netplan
      tags: [networking]

    # Firewall (nftables) configuration
    - role: ricsanfre.firewall
      tags: [firewall]

    # NTP Server configuration
    - role: ricsanfre.ntp
      tags: [ntp]

- name: Configure External Node
  hosts: service0
  gather_facts: true
  tags: [external]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]

    # SSH configuration and hardening
    - role: willshersystems.sshd
      tags: [security]

    # NTP Client configuration
    - role: ricsanfre.ntp
      tags: [ntp]

- name: Configure Pi Cluster Nodes
  hosts: k3s_cluster
  gather_facts: true
  tags: [node]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]

    # SSH configuration and hardening
    - role: willshersystems.sshd
      tags: [security]

    # NTP Client configuration
    - role: ricsanfre.ntp
      tags: [ntp]

  tasks:
    # Local Storage configuration
    - name: Dedicated Disks
      block:
        # iSCSI client (initiator) configuration
        # iSCSI initiator needs to be configured for Longhorn
        - name: Configure iSCSI Initiator
          include_role:
            name: ricsanfre.iscsi_initiator
          vars:
            open_iscsi_initiator_name: "iqn.2025-06.com.changeme.longhorn:{{ ansible_facts['nodename'] }}"
            open_iscsi_automatic_startup: true
      tags: [storage]
