---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt:
        upgrade: safe

    - name: Autoclean and autoremove
      apt:
        autoclean: true
        autoremove: true

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
        get_checksum: false
        # Algorithm to determine checksum of file
      register: reboot_required_file
      # Save a result in and we are going to use it as follows to reboot the box

    - name: Reboot if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
        # Execute uptime command on the rebooted server and expect success from
        # to determine the machine is ready for further tasks
      when: reboot_required_file.stat.exists
      # First, check that the file named /var/run/reboot-required exists using a
      # variable named reboot_required_file.
      # The reboot module will only work if that file exists and it is enforced
      # using ‘when: reboot_required_file.stat.exists’ Ansible condition.
