apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# patch values.yaml?
configMapGenerator:
  - name: velero-helm-values
    behavior: merge
    files:
      - monitoring-values.yaml=values.yaml

patches:
- target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: velero
  path: helm-patch.yaml