---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/metrics-server/app/overlays/dev
  prune: true
  wait: true
